In [1]:
import findspark
findspark.init()

In [2]:
from pyspark import SparkContext
sc = SparkContext.getOrCreate()

In [4]:
from pyspark.sql import SparkSession
from pyspark import SparkContext, SparkConf

In [41]:
sc

<SparkContext master=local[*] appName=pyspark-shell>

In [42]:
data = [1, 2, 3, 4, 5]
distData = sc.parallelize(data)
distData.count()

5

In [43]:
distFile = sc.textFile("employee.txt")

In [44]:
distFile.count()

1001

In [13]:
distFile.collect()

['id,last_name,email,gender,department,start_date,salary,job_title,region_id',
 "1,'Kelley','rkelley0@soundcloud.com','Female','Computers','10/2/2009',67470,'Structural Engineer',2",
 "2,'Armstrong','sarmstrong1@infoseek.co.jp','Male','Sports','3/31/2008',71869,'Financial Advisor',2",
 "3,'Carr','fcarr2@woothemes.com','Male','Automotive','7/12/2009',101768,'Recruiting Manager',3",
 "4,'Murray','jmurray3@gov.uk','Female','Jewelery','12/25/2014',96897,'Desktop Support Technician',3",
 "5,'Ellis','jellis4@sciencedirect.com','Female','Grocery','9/19/2002',63702,'Software Engineer III',7",
 "6,'Phillips','bphillips5@time.com','Male','Tools','8/21/2013',118497,'Executive Secretary',1",
 "7,'Williamson','rwilliamson6@ted.com','Male','Computers','5/14/2006',65889,'Dental Hygienist',6",
 "8,'Harris','aharris7@ucoz.com','Female','Toys','8/12/2003',84427,'Safety Technician I',4",
 "9,'James','rjames8@prnewswire.com','Male','Jewelery','9/7/2005',108657,'Sales Associate',2",
 "10,'Sanchez','rsanche

In [45]:
from pyspark.sql.types import StructType
from pyspark.sql.types import StructField
from pyspark.sql.types import StringType
from pyspark.sql.types import Row

In [46]:
spark = SparkSession.builder.appName("pyspark").config("spark.som.config", "some-value").getOrCreate()

In [47]:
spark
from pyspark.sql.types import *

In [48]:
from pyspark.sql import SQLContext
sqlContext = SQLContext(sc)

In [49]:
distFile.take(5)

['id,last_name,email,gender,department,start_date,salary,job_title,region_id',
 "1,'Kelley','rkelley0@soundcloud.com','Female','Computers','10/2/2009',67470,'Structural Engineer',2",
 "2,'Armstrong','sarmstrong1@infoseek.co.jp','Male','Sports','3/31/2008',71869,'Financial Advisor',2",
 "3,'Carr','fcarr2@woothemes.com','Male','Automotive','7/12/2009',101768,'Recruiting Manager',3",
 "4,'Murray','jmurray3@gov.uk','Female','Jewelery','12/25/2014',96897,'Desktop Support Technician',3"]

In [50]:
readJson = spark.read.json("names.json")

In [51]:
readJson.show()

+--------------------+
|     _corrupt_record|
+--------------------+
|{\rtf1\ansi\ansic...|
|{\fonttbl\f0\fnil...|
|{\colortbl;\red25...|
|\red6\green33\blu...|
|{\*\expandedcolor...|
|\cssrgb\c1176\c18...|
|\margl1440\margr1...|
|          \deftab720|
|\itap1\trowd \taf...|
|\clvertalt \clshd...|
|\clmrg \clvertalt...|
|\pard\intbl\itap1...|
|\f0\fs24 \cf2 \ex...|
|\outl0\strokewidt...|
|\pard\intbl\itap1...|
|\itap1\trowd \taf...|
|\clvertalt \clshd...|
|\clvertalt \clshd...|
|\pard\intbl\itap1...|
|\cf6 \strokec6 \c...|
+--------------------+
only showing top 20 rows



In [52]:
cdata = spark.read.json("customerData.json")

In [53]:
cdata.show()

+---+------+------+-----------------+------+
|age|deptid|gender|             name|salary|
+---+------+------+-----------------+------+
| 32|   100|  male|Benjamin Garrison|  3000|
| 40|   200|  male|    Holland Drake|  4500|
| 26|   100|  male|  Burks Velasquez|  2700|
| 51|   100|female|    June Rutledge|  4300|
| 44|   200|  male|    Nielsen Knapp|  6500|
+---+------+------+-----------------+------+



In [54]:
cdata.head(4)

[Row(age='32', deptid='100', gender='male', name='Benjamin Garrison', salary='3000'),
 Row(age='40', deptid='200', gender='male', name='Holland Drake', salary='4500'),
 Row(age='26', deptid='100', gender='male', name='Burks Velasquez', salary='2700'),
 Row(age='51', deptid='100', gender='female', name='June Rutledge', salary='4300')]

In [55]:
cdata.take(2)

[Row(age='32', deptid='100', gender='male', name='Benjamin Garrison', salary='3000'),
 Row(age='40', deptid='200', gender='male', name='Holland Drake', salary='4500')]

In [56]:
cdata.schema()

TypeError: 'StructType' object is not callable

In [58]:
cdata.select("name","deptid").show()

+-----------------+------+
|             name|deptid|
+-----------------+------+
|Benjamin Garrison|   100|
|    Holland Drake|   200|
|  Burks Velasquez|   100|
|    June Rutledge|   100|
|    Nielsen Knapp|   200|
+-----------------+------+



In [60]:
cdata.describe().show()

+-------+-----------------+------------------+------+-----------------+------------------+
|summary|              age|            deptid|gender|             name|            salary|
+-------+-----------------+------------------+------+-----------------+------------------+
|  count|                5|                 5|     5|                5|                 5|
|   mean|             38.6|             140.0|  null|             null|            4200.0|
| stddev|9.838699100999076|54.772255750516614|  null|             null|1506.6519173319364|
|    min|               26|               100|female|Benjamin Garrison|              2700|
|    max|               51|               200|  male|    Nielsen Knapp|              6500|
+-------+-----------------+------------------+------+-----------------+------------------+



In [62]:
cdata.columns

['age', 'deptid', 'gender', 'name', 'salary']

In [68]:
cdata.printSchema()

root
 |-- age: string (nullable = true)
 |-- deptid: string (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- salary: string (nullable = true)



In [69]:
cdata.explain()

== Physical Plan ==
*FileScan json [age#38,deptid#39,gender#40,name#41,salary#42] Batched: false, Format: JSON, Location: InMemoryFileIndex[file:/Users/subbuch/customerData.json], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<age:string,deptid:string,gender:string,name:string,salary:string>


In [70]:
# groupBy operation
cdata.groupBy("age").count().show()

+---+-----+
|age|count|
+---+-----+
| 51|    1|
| 26|    1|
| 40|    1|
| 44|    1|
| 32|    1|
+---+-----+



In [71]:
#filter opertaion 

cdata.filter(cdata["age"] > 24).show()

+---+------+------+-----------------+------+
|age|deptid|gender|             name|salary|
+---+------+------+-----------------+------+
| 32|   100|  male|Benjamin Garrison|  3000|
| 40|   200|  male|    Holland Drake|  4500|
| 26|   100|  male|  Burks Velasquez|  2700|
| 51|   100|female|    June Rutledge|  4300|
| 44|   200|  male|    Nielsen Knapp|  6500|
+---+------+------+-----------------+------+



In [73]:
#sort
cdata.sort(cdata.age.desc()).collect()

[Row(age='51', deptid='100', gender='female', name='June Rutledge', salary='4300'),
 Row(age='44', deptid='200', gender='male', name='Nielsen Knapp', salary='6500'),
 Row(age='40', deptid='200', gender='male', name='Holland Drake', salary='4500'),
 Row(age='32', deptid='100', gender='male', name='Benjamin Garrison', salary='3000'),
 Row(age='26', deptid='100', gender='male', name='Burks Velasquez', salary='2700')]

In [74]:
cdata.sort("age", ascending = False).collect()

[Row(age='51', deptid='100', gender='female', name='June Rutledge', salary='4300'),
 Row(age='44', deptid='200', gender='male', name='Nielsen Knapp', salary='6500'),
 Row(age='40', deptid='200', gender='male', name='Holland Drake', salary='4500'),
 Row(age='32', deptid='100', gender='male', name='Benjamin Garrison', salary='3000'),
 Row(age='26', deptid='100', gender='male', name='Burks Velasquez', salary='2700')]

In [75]:
cdata.orderBy(["age","name"], ascending=[0,1]).collect()

[Row(age='51', deptid='100', gender='female', name='June Rutledge', salary='4300'),
 Row(age='44', deptid='200', gender='male', name='Nielsen Knapp', salary='6500'),
 Row(age='40', deptid='200', gender='male', name='Holland Drake', salary='4500'),
 Row(age='32', deptid='100', gender='male', name='Benjamin Garrison', salary='3000'),
 Row(age='26', deptid='100', gender='male', name='Burks Velasquez', salary='2700')]

In [83]:
housedata = spark.read.csv("housing.csv", header= True)

In [84]:
housedata.take(2)

[Row(longitude='-122.23', latitude='37.88', housing_median_age='41.0', total_rooms='880.0', total_bedrooms='129.0', population='322.0', households='126.0', median_income='8.3252', median_house_value='452600.0', ocean_proximity='NEAR BAY'),
 Row(longitude='-122.22', latitude='37.86', housing_median_age='21.0', total_rooms='7099.0', total_bedrooms='1106.0', population='2401.0', households='1138.0', median_income='8.3014', median_house_value='358500.0', ocean_proximity='NEAR BAY')]

In [86]:
housedata.show(5)

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              

In [87]:
housedata.take(2)

[Row(longitude='-122.23', latitude='37.88', housing_median_age='41.0', total_rooms='880.0', total_bedrooms='129.0', population='322.0', households='126.0', median_income='8.3252', median_house_value='452600.0', ocean_proximity='NEAR BAY'),
 Row(longitude='-122.22', latitude='37.86', housing_median_age='21.0', total_rooms='7099.0', total_bedrooms='1106.0', population='2401.0', households='1138.0', median_income='8.3014', median_house_value='358500.0', ocean_proximity='NEAR BAY')]

In [88]:
housedata.describe().show()

+-------+-------------------+-----------------+------------------+------------------+------------------+------------------+-----------------+------------------+------------------+---------------+
|summary|          longitude|         latitude|housing_median_age|       total_rooms|    total_bedrooms|        population|       households|     median_income|median_house_value|ocean_proximity|
+-------+-------------------+-----------------+------------------+------------------+------------------+------------------+-----------------+------------------+------------------+---------------+
|  count|              20640|            20640|             20640|             20640|             20433|             20640|            20640|             20640|             20640|          20640|
|   mean|-119.56970445736148| 35.6318614341087|28.639486434108527|2635.7630813953488| 537.8705525375618|1425.4767441860465|499.5396802325581|3.8706710029070246|206855.81690891474|           null|
| stddev|  2.0035317

In [90]:
housedata.printSchema()

root
 |-- longitude: string (nullable = true)
 |-- latitude: string (nullable = true)
 |-- housing_median_age: string (nullable = true)
 |-- total_rooms: string (nullable = true)
 |-- total_bedrooms: string (nullable = true)
 |-- population: string (nullable = true)
 |-- households: string (nullable = true)
 |-- median_income: string (nullable = true)
 |-- median_house_value: string (nullable = true)
 |-- ocean_proximity: string (nullable = true)



In [92]:
housedata.dtypes

[('longitude', 'string'),
 ('latitude', 'string'),
 ('housing_median_age', 'string'),
 ('total_rooms', 'string'),
 ('total_bedrooms', 'string'),
 ('population', 'string'),
 ('households', 'string'),
 ('median_income', 'string'),
 ('median_house_value', 'string'),
 ('ocean_proximity', 'string')]

In [93]:
housedata.distinct().count()

20640

In [94]:
housedata.explain()

== Physical Plan ==
*FileScan csv [longitude#878,latitude#879,housing_median_age#880,total_rooms#881,total_bedrooms#882,population#883,households#884,median_income#885,median_house_value#886,ocean_proximity#887] Batched: false, Format: CSV, Location: InMemoryFileIndex[file:/Users/subbuch/housing.csv], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<longitude:string,latitude:string,housing_median_age:string,total_rooms:string,total_bedroo...


In [97]:
housedata = housedata.withColumnRenamed('total_rooms','rooms')

In [100]:
housedata.select("rooms").show(2)

+------+
| rooms|
+------+
| 880.0|
|7099.0|
+------+
only showing top 2 rows



In [104]:
housedata = housedata.withColumnRenamed('rooms','total_rooms')

In [106]:
housedata.show(10).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              

AttributeError: 'NoneType' object has no attribute 'show'

In [107]:
housedata.createTempView("housingData")

In [109]:
sqlData = spark.sql("SELECT * FROM  housingData").show(10)

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              

In [110]:
# converting DataFrame into RDD

rdd1 = housedata.rdd

In [114]:
# Quries. on DataFrames 

housedata.select("total_rooms","total_bedrooms").show(5)

+-----------+--------------+
|total_rooms|total_bedrooms|
+-----------+--------------+
|      880.0|         129.0|
|     7099.0|        1106.0|
|     1467.0|         190.0|
|     1274.0|         235.0|
|     1627.0|         280.0|
+-----------+--------------+
only showing top 5 rows



In [118]:
from pyspark.sql.functions import explode

In [124]:
import numpy as np

In [125]:
from pyspark.mllib.stat import Statistics

In [126]:
mat = sc.parallelize(
    [np.array([1.0, 10.0, 100.0]), np.array([2.0, 20.0, 200.0]), np.array([3.0, 30.0, 300.0])]
)

In [127]:
summary = Statistics.colStats(mat)

In [128]:
print(summary.mean())

[  2.  20. 200.]


In [129]:
print(summary.variance())

[1.e+00 1.e+02 1.e+04]


In [130]:
print(summary.numNonzeros()) 

[3. 3. 3.]


In [131]:
seriesX = sc.parallelize([1.0, 2.0, 3.0, 3.0, 5.0])  # a series
# seriesY must have the same number of partitions and cardinality as seriesX
seriesY = sc.parallelize([11.0, 22.0, 33.0, 33.0, 555.0])

In [132]:
print("Correlation is: " + str(Statistics.corr(seriesX, seriesY, method="pearson")))

data = sc.parallelize(
    [np.array([1.0, 10.0, 100.0]), np.array([2.0, 20.0, 200.0]), np.array([5.0, 33.0, 366.0])]
)  # an RDD of Vectors

# calculate the correlation matrix using Pearson's method. Use "spearman" for Spearman's method.
# If a method is not specified, Pearson's method will be used by default.
print(Statistics.corr(data, method="pearson"))

Correlation is: 0.8500286768773001
[[1.         0.97888347 0.99038957]
 [0.97888347 1.         0.99774832]
 [0.99038957 0.99774832 1.        ]]


In [133]:
from pyspark.mllib.linalg import Matrices, Vectors
from pyspark.mllib.regression import LabeledPoint
from pyspark.mllib.stat import Statistics

In [134]:
vec = Vectors.dense(0.1, 0.15, 0.2, 0.3, 0.25) 

In [135]:
goodnessOfFitTestResult = Statistics.chiSqTest(vec)

In [136]:
print("%s\n" % goodnessOfFitTestResult)


Chi squared test summary:
method: pearson
degrees of freedom = 4 
statistic = 0.12499999999999999 
pValue = 0.998126379239318 
No presumption against null hypothesis: observed follows the same distribution as expected..



In [137]:
mat = Matrices.dense(3, 2, [1.0, 3.0, 5.0, 2.0, 4.0, 6.0])  # a contingency matrix


In [138]:
# conduct Pearson's independence test on the input contingency matrix
independenceTestResult = Statistics.chiSqTest(mat)

In [139]:
# summary of the test including the p-value, degrees of freedom,
# test statistic, the method used, and the null hypothesis.
print("%s\n" % independenceTestResult)

obs = sc.parallelize(
    [LabeledPoint(1.0, [1.0, 0.0, 3.0]),
     LabeledPoint(1.0, [1.0, 2.0, 0.0]),
     LabeledPoint(1.0, [-1.0, 0.0, -0.5])]
)  # LabeledPoint(label, feature)

Chi squared test summary:
method: pearson
degrees of freedom = 2 
statistic = 0.14141414141414144 
pValue = 0.931734784568187 
No presumption against null hypothesis: the occurrence of the outcomes is statistically independent..



In [140]:
featureTestResults = Statistics.chiSqTest(obs)

for i, result in enumerate(featureTestResults):
    print("Column %d:\n%s" % (i + 1, result))

Column 1:
Chi squared test summary:
method: pearson
degrees of freedom = 0 
statistic = 0.0 
pValue = 1.0 
No presumption against null hypothesis: the occurrence of the outcomes is statistically independent..
Column 2:
Chi squared test summary:
method: pearson
degrees of freedom = 0 
statistic = 0.0 
pValue = 1.0 
No presumption against null hypothesis: the occurrence of the outcomes is statistically independent..
Column 3:
Chi squared test summary:
method: pearson
degrees of freedom = 0 
statistic = 0.0 
pValue = 1.0 
No presumption against null hypothesis: the occurrence of the outcomes is statistically independent..


In [141]:
parallelData = sc.parallelize([0.1, 0.15, 0.2, 0.3, 0.25])

# run a KS test for the sample versus a standard normal distribution
testResult = Statistics.kolmogorovSmirnovTest(parallelData, "norm", 0, 1)
# summary of the test including the p-value, test statistic, and null hypothesis
# if our p-value indicates significance, we can reject the null hypothesis
# Note that the Scala functionality of calling Statistics.kolmogorovSmirnovTest with
# a lambda to calculate the CDF is not made available in the Python API
print(testResult)

Kolmogorov-Smirnov test summary:
degrees of freedom = 0 
statistic = 0.539827837277029 
pValue = 0.06821463111921133 
Low presumption against null hypothesis: Sample follows theoretical distribution.


In [142]:
from pyspark.ml.classification import LogisticRegression


In [143]:
training = housedata

In [144]:
lr = LogisticRegression(maxIter=10, regParam=0.3, elasticNetParam=0.8)
