In [1]:
import numpy as np

In [3]:
L = list(range(10))

In [4]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
type(L[0])

int

In [7]:
l2 = [str(c) for c in L]

In [8]:
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [9]:
type(l2)

list

In [10]:
import array

In [ ]:
# creating an array using list

In [12]:
l = list(range(10))

In [17]:
A= array.array('i', l)

In [18]:
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# creating an array using numpy 

In [19]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [ ]:
# you can specify the data type by explicitly

In [20]:
np.array([1,2,3,4,5,6], dtype='float32')

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [ ]:
# Nested lists results into multidmensional array

In [22]:
nd = np.array([range(i,i+3) for i in [2,4,6]])

In [23]:
nd

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [24]:
type(nd)

numpy.ndarray

In [ ]:
# creating an array from scratch using Built ins functions, array with zeros

In [27]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones((3,5), dtype = float)  # creating an array with ones of 3 rows and 5 columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
 # create an array with linear sequence
    
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
# evenly spaced array
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
# Uniformly distributed array

np.random.random((3,3))

array([[0.82008864, 0.56300122, 0.73946621],
       [0.28430626, 0.42759989, 0.65816436],
       [0.44125749, 0.79931759, 0.20686326]])

In [37]:
# Normally distributed array values
# with Mean 0 and Std 1

np.random.normal(0,1,(3,3))

array([[ 0.28281126, -0.68914207, -0.97487671],
       [ 0.74091396,  0.32393587, -1.0599971 ],
       [ 0.53412784, -0.14080674, -0.03286193]])

In [38]:
# array of random inters

np.random.randint(0,10,(3,3))

array([[1, 2, 3],
       [9, 0, 9],
       [2, 4, 1]])

In [39]:
# identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that 
# memory location

np.empty(3)

array([1., 1., 1.])

# Array Manipulation 

If you want to do Array Manipulation , 
you have to understand  the Attributes of array, Indexing of array, Slicing of array, Reshaping of Arrays, Joining and Splitting of Arrays.

Each Array has atrributes like ndim(number of dimensions), shape(size of each diemension) and Size(total size of the array)

In [41]:
np.random.seed(0) # seed for reproducibility

In [53]:
#One diemensional array
a1 = np.random.randint(10, size=6)
print("a1 ndim: ", a1.ndim)
print("a1 shape:", a1.shape)
print("x1 size: ", a1.size)

a1

a1 ndim:  1
a1 shape: (6,)
x1 size:  6


array([3, 3, 7, 8, 5, 0])

In [52]:
# Two-Diemensional array
a2 = np.random.randint(10, size = (3,4))
print("a2 ndim: ", a2.ndim)
print("a2 shape:", a2.shape)
print("x2 size: ", a2.size)

a2

a2 ndim:  2
a2 shape: (3, 4)
x2 size:  12


array([[8, 4, 7, 0],
       [4, 9, 0, 6],
       [4, 2, 4, 6]])

In [54]:
# Three-Diemensional array
a3 = np.random.randint(10,size = (3,4,5))

print("a3 ndim: ", a3.ndim)
print("a3 shape:", a3.shape)
print("x3 size: ", a3.size)

a3

a3 ndim:  3
a3 shape: (3, 4, 5)
x3 size:  60


array([[[8, 5, 4, 7, 4],
        [1, 3, 3, 9, 2],
        [5, 2, 3, 5, 7],
        [2, 7, 1, 6, 5]],

       [[0, 0, 3, 1, 9],
        [9, 6, 6, 7, 8],
        [8, 7, 0, 8, 6],
        [8, 9, 8, 3, 6]],

       [[1, 7, 4, 9, 2],
        [0, 8, 2, 7, 8],
        [4, 4, 1, 7, 6],
        [9, 4, 1, 5, 9]]])

In [55]:
# Array Indexing 

a1

array([3, 3, 7, 8, 5, 0])

In [56]:
# you can have the '0' position element in array a1 by using '[]' brackets 
a1[0]

3

In [58]:
a1[-2] # you can use negative indices too 

5

In [62]:
# index in multidiemensional array

a2[0,0]
a2[2,3]
a2[2,-1]

6

In [63]:
# you can modify the values of indices

a2[0,0]= 12

In [64]:
a2

array([[12,  4,  7,  0],
       [ 4,  9,  0,  6],
       [ 4,  2,  4,  6]])

In [65]:
a1[0] = 3.14159

In [66]:
a1

array([3, 3, 7, 8, 5, 0])

In [ ]:
# Array Slicing



In [67]:
x = np.arange(10)

In [68]:
x[0]

0

In [70]:
# first 5 elements in the array
x[:5]

array([0, 1, 2, 3, 4])

In [71]:
# elements from index 5
x[5:]

array([5, 6, 7, 8, 9])

In [72]:
# sub-array

x[4:7]

array([4, 5, 6])

In [74]:
# Reverse all elements in the array
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [75]:
# Multidiemensional subarrays

a2[:2,:3] # 2 rows, 3 columns

array([[12,  4,  7],
       [ 4,  9,  0]])

In [78]:
a2[:3,::2] # all rows ,  every other column

array([[12,  7],
       [ 4,  0],
       [ 4,  4]])

In [82]:
a2

array([[12,  4,  7,  0],
       [ 4,  9,  0,  6],
       [ 4,  2,  4,  6]])

In [80]:
# Accessing rows and columns

print(a2[:,0]) # first column of a2

[12  4  4]


In [81]:
print(a2[0,:]) # first row of a2 

[12  4  7  0]


In [87]:
# sub-arrays as no-copy views

a2_sub_arr_copy = a2[:2,:2] 

In [88]:
print(a2_sub_arr_copy)

[[12  4]
 [ 4  9]]


In [90]:
# modify the sub-array elements

a2_sub_arr_copy[0,0]= 99

a2_sub_arr_copy

array([[99,  4],
       [ 4,  9]])

In [91]:
# Creating copies of arrays

a2_sub_copy = a2[:2,:2].copy()

Statement 1 :a2_sub_arr_copy = a2[:2,:2]  and  
Statement 2 : a2_sub_copy = a2[:2,:2].copy()    #these to statements are equal, 
In second statemnet using copy() method to copy the sub-array from array 'a2' by using index

In [92]:
a2_sub_copy

array([[99,  4],
       [ 4,  9]])

In [99]:
# Reshaping of Arrays

arr = np.arange(1,10)  # 1D array

#arr = np.arange(1,10).reshape(3,3)
arr.reshape(3,3) # reshaping the 1D array into 3*3 array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
# Array Concatenation 

a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [104]:
ndarray = np.array([[6,7,8],[9,6,9]])

In [105]:
np.concatenate([ndarray,ndarray])

array([[6, 7, 8],
       [9, 6, 9],
       [6, 7, 8],
       [9, 6, 9]])

In [107]:
# Splitting of Arrays

x=[1,2,3,99,99,3,2,1] 
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [109]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
upper, lower = np.vsplit(grid, [2]) 
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [112]:
left, right = np.hsplit(grid, [2]) 
print(left)
print(right)


[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
